#!/usr/bin/env python3
# ---------------------------------------------------------
# urdf2mpc.py — acados OCP code generator for libflorid MPC
#
# 用法:
#   python3 urdf2mpc.py --urdf <path.urdf> --outdir <dir> --name WillowMPCTraits
#
# 输出:
#   WillowMPCTraits.hpp — C++ traits 头文件, 包含:
#     1. CasADi 外部函数 (动力学, 代价, 约束)
#     2. acados NLP solver 包装器
#     3. C++ traits 封装 (create/destroy/solve/get)
# ---------------------------------------------------------

import os, re, sys, argparse
import numpy as np
import casadi as ca

try:
    import pinocchio as pin
    import pinocchio.casadi as cpin
except ImportError:
    print("ERROR: pinocchio with CasADi required.", file=sys.stderr)
    print("Install: conda install -c conda-forge pinocchio", file=sys.stderr)
    sys.exit(1)

from acados_template import AcadosOcp, AcadosModel


NQ, NV, NX, NU = 6, 6, 12, 6


def build_explicit_dynamics(urdf_path):
    model = pin.buildModelFromUrdf(urdf_path)
    cmodel = cpin.Model(model)
    cdata = cmodel.createData()

    ee_joint_id = cmodel.njoints - 1
    g_vec = ca.SX([0.0, 0.0, -9.81])

    x    = ca.SX.sym('x',  NX)
    u    = ca.SX.sym('u',  NU)
    xdot = ca.SX.sym('xdot', NX)

    q   = x[:NQ]
    dq  = x[NQ:]
    tau = u

    cpin.forwardKinematics(cmodel, cdata, q)
    cpin.updateFramePlacements(cmodel, cdata)
    T_fk = cdata.oMi[ee_joint_id].homogeneous
    fk_trans = T_fk[12:15]

    cpin.crba(cmodel, cdata, q)
    M = cdata.M

    cpin.computeCoriolisMatrix(cmodel, cdata, q, dq)
    C_times_dq = ca.mtimes(cdata.C, dq)

    cmodel.gravity = cpin.Motion(g_vec, ca.SX.zeros(3))
    cpin.computeGeneralizedGravity(cmodel, cdata, q)
    g_out = cdata.g

    tau_net = tau - C_times_dq - g_out
    ddq = ca.solve(M, tau_net)

    f_expl = ca.vertcat(dq, ddq)
    f_impl = xdot - f_expl
    return f_expl, f_impl, x, u, xdot, fk_trans


def build_acados_ocp(f_expl, f_impl, x, u, xdot, fk_trans, horizon=5, dt=0.004):
    model = AcadosModel()
    model.name = 'willow_mpc'
    model.x = x; model.xdot = xdot; model.u = u
    model.f_expl_expr = f_expl; model.f_impl_expr = f_impl

    q_lower = np.array([-3.14, 0.0, 0.0, -1.3, -1.57, -1.57])
    q_upper = np.array([ 3.14, 3.14, 3.14, 1.3,  1.57,  1.57])
    tau_limit = np.array([5.0, 5.0, 5.0, 3.0, 3.0, 3.0])
    dq_limit = np.array([12.48, 3.744, 3.744, 12.48, 12.48, 12.48])

    ocp = AcadosOcp()
    ocp.model = model
    ocp.solver_options.N_horizon = horizon
    ocp.solver_options.tf = horizon * dt
    ocp.solver_options.qp_solver = 'FULL_CONDENSING_HPIPM'
    ocp.solver_options.hessian_approx = 'GAUSS_NEWTON'
    ocp.solver_options.integrator_type = 'ERK'
    ocp.solver_options.nlp_solver_type = 'SQP_RTI'
    ocp.solver_options.nlp_solver_max_iter = 5
    ocp.solver_options.levenberg_marquardt = 1e-4
    ocp.solver_options.globalization = 'FIXED_STEP'

    q_expr = x[:NQ]; dq_expr = x[NQ:]; tau_expr = u
    ocp.model.cost_y_expr   = ca.vertcat(fk_trans, dq_expr, tau_expr)
    ocp.model.cost_y_expr_e = ca.vertcat(fk_trans, dq_expr)

    ny, ny_e = 15, 9
    W_pos  = np.diag([10., 10., 10.]); W_vel = np.diag([1.]*NQ)
    W_tau  = np.diag([0.01]*NU)
    Wpos_e = np.diag([50., 50., 50.]); Wvel_e = np.diag([2.]*NQ)

    ocp.cost.cost_type = ocp.cost.cost_type_e = 'NONLINEAR_LS'
    ocp.cost.W = ca.diagcat(W_pos, W_vel, W_tau).full()
    ocp.cost.W_e = ca.diagcat(Wpos_e, Wvel_e).full()
    ocp.cost.yref = np.zeros(ny); ocp.cost.yref_e = np.zeros(ny_e)

    ocp.constraints.x0 = np.zeros(NX)
    ocp.constraints.lbx = np.concatenate([q_lower, -dq_limit])
    ocp.constraints.ubx = np.concatenate([q_upper,  dq_limit])
    ocp.constraints.idxbx = np.arange(NX); ocp.dims.nbx = NX
    ocp.constraints.lbu = -tau_limit; ocp.constraints.ubu = tau_limit
    ocp.constraints.idxbu = np.arange(NU); ocp.dims.nbu = NU
    ocp.constraints.lbx_0 = np.concatenate([np.full(NQ, -1e6), -dq_limit])
    ocp.constraints.ubx_0 = np.concatenate([np.full(NQ,  1e6),  dq_limit])
    ocp.constraints.idxbx_0 = np.arange(NX); ocp.dims.nbx_0 = NX

    ocp.code_gen_options.code_export_directory = 'c_generated_code'
    ocp.code_gen_options.json_file = 'acados_ocp_willow.json'

    meta = {
        'nx': NX, 'nu': NU, 'nq': NQ, 'horizon': horizon, 'dt': dt,
        'q_lower': q_lower, 'q_upper': q_upper,
        'tau_limit': tau_limit, 'dq_limit': dq_limit,
        'ny': ny, 'ny_e': ny_e,
    }
    return ocp, meta


SOLVER_HEADER_TEMPLATE = """/*
 * acados_solver_willow_mpc.h — MPC solver for Willow arm
 * Auto-generated by urdf2mpc.py
 */
#ifndef ACADOS_SOLVER_WILLOW_MPC_H_
#define ACADOS_SOLVER_WILLOW_MPC_H_

#include "acados/utils/types.h"
#include "acados_c/ocp_nlp_interface.h"
#include "acados_c/external_function_interface.h"

#define WILLOW_MPC_NX     {NX}
#define WILLOW_MPC_NZ     0
#define WILLOW_MPC_NU     {NU}
#define WILLOW_MPC_NP     0
#define WILLOW_MPC_NP_GLOBAL 0

#define WILLOW_MPC_NBX    {NX}
#define WILLOW_MPC_NBX0   {NX}
#define WILLOW_MPC_NBU    {NU}
#define WILLOW_MPC_NSBX   0
#define WILLOW_MPC_NSBU   0
#define WILLOW_MPC_NSH    0
#define WILLOW_MPC_NSH0   0
#define WILLOW_MPC_NSG    0
#define WILLOW_MPC_NSPHI  0
#define WILLOW_MPC_NSHN   0
#define WILLOW_MPC_NSGN   0
#define WILLOW_MPC_NSPHIN 0
#define WILLOW_MPC_NSPHI0 0
#define WILLOW_MPC_NSBXN  0
#define WILLOW_MPC_NS     0
#define WILLOW_MPC_NS0    0
#define WILLOW_MPC_NSN    0
#define WILLOW_MPC_NG     0
#define WILLOW_MPC_NBXN   0
#define WILLOW_MPC_NGN    0
#define WILLOW_MPC_NY0    0
#define WILLOW_MPC_NY     {NY}
#define WILLOW_MPC_NYN    {NYE}
#define WILLOW_MPC_N      {HORIZON}
#define WILLOW_MPC_NH     0
#define WILLOW_MPC_NHN    0
#define WILLOW_MPC_NH0    0
#define WILLOW_MPC_NPHI0  0
#define WILLOW_MPC_NPHI   0
#define WILLOW_MPC_NPHIN  0
#define WILLOW_MPC_NR     0

#ifdef __cplusplus
extern "C" {{
#endif

typedef struct willow_mpc_solver_capsule {{
    ocp_nlp_in *nlp_in;
    ocp_nlp_out *nlp_out;
    ocp_nlp_out *sens_out;
    ocp_nlp_solver *nlp_solver;
    void *nlp_opts;
    ocp_nlp_plan_t *nlp_solver_plan;
    ocp_nlp_config *nlp_config;
    ocp_nlp_dims *nlp_dims;

    unsigned int nlp_np;

    // dynamics (ERK: N per-stage copies)
    external_function_external_param_casadi *expl_ode_fun;
    external_function_external_param_casadi *expl_vde_for;
    external_function_external_param_casadi *expl_vde_adj;

    // cost path (N-1 copies for stages 1..N-1)
    external_function_external_param_casadi *cost_y_fun;
    external_function_external_param_casadi *cost_y_fun_jac_ut_xt;
    external_function_external_param_casadi *cost_y_hess;

    // cost terminal (single, stage N)
    external_function_external_param_casadi cost_y_e_fun;
    external_function_external_param_casadi cost_y_e_fun_jac_ut_xt;
    external_function_external_param_casadi cost_y_e_hess;
}} willow_mpc_solver_capsule;

willow_mpc_solver_capsule * willow_mpc_acados_create_capsule(void);
int willow_mpc_acados_free_capsule(willow_mpc_solver_capsule *cap);
int willow_mpc_acados_create(willow_mpc_solver_capsule *cap);
int willow_mpc_acados_solve(willow_mpc_solver_capsule *cap);
int willow_mpc_acados_free(willow_mpc_solver_capsule *cap);

ocp_nlp_in     *willow_mpc_acados_get_nlp_in(willow_mpc_solver_capsule*);
ocp_nlp_out    *willow_mpc_acados_get_nlp_out(willow_mpc_solver_capsule*);
ocp_nlp_solver *willow_mpc_acados_get_nlp_solver(willow_mpc_solver_capsule*);
ocp_nlp_config *willow_mpc_acados_get_nlp_config(willow_mpc_solver_capsule*);
void           *willow_mpc_acados_get_nlp_opts(willow_mpc_solver_capsule*);
ocp_nlp_dims   *willow_mpc_acados_get_nlp_dims(willow_mpc_solver_capsule*);
ocp_nlp_plan_t *willow_mpc_acados_get_nlp_plan(willow_mpc_solver_capsule*);

#ifdef __cplusplus
}}
#endif

#endif
"""

SOLVER_SOURCE_TEMPLATE = """/*
 * acados_solver_willow_mpc.c — MPC solver for Willow arm (ERK + NLS cost)
 */
#include "acados_solver_willow_mpc.h"
#include "acados_c/ocp_nlp_interface.h"
#include "acados_c/external_function_interface.h"
#include <stdlib.h>

// CasADi external functions
extern void willow_mpc_expl_ode_fun(void);
extern int  willow_mpc_expl_ode_fun_n_in(void);
extern int  willow_mpc_expl_ode_fun_n_out(void);
extern int  willow_mpc_expl_ode_fun_sparsity_in(int);
extern int  willow_mpc_expl_ode_fun_sparsity_out(int);

extern void willow_mpc_expl_vde_forw(void);
extern int  willow_mpc_expl_vde_forw_n_in(void);
extern int  willow_mpc_expl_vde_forw_n_out(void);
extern int  willow_mpc_expl_vde_forw_sparsity_in(int);
extern int  willow_mpc_expl_vde_forw_sparsity_out(int);

extern void willow_mpc_expl_vde_adj(void);
extern int  willow_mpc_expl_vde_adj_n_in(void);
extern int  willow_mpc_expl_vde_adj_n_out(void);
extern int  willow_mpc_expl_vde_adj_sparsity_in(int);
extern int  willow_mpc_expl_vde_adj_sparsity_out(int);

extern void willow_mpc_cost_y_fun(void);
extern int  willow_mpc_cost_y_fun_n_in(void);
extern int  willow_mpc_cost_y_fun_n_out(void);
extern int  willow_mpc_cost_y_fun_sparsity_in(int);
extern int  willow_mpc_cost_y_fun_sparsity_out(int);

extern void willow_mpc_cost_y_fun_jac_ut_xt(void);
extern int  willow_mpc_cost_y_fun_jac_ut_xt_n_in(void);
extern int  willow_mpc_cost_y_fun_jac_ut_xt_n_out(void);
extern int  willow_mpc_cost_y_fun_jac_ut_xt_sparsity_in(int);
extern int  willow_mpc_cost_y_fun_jac_ut_xt_sparsity_out(int);

extern void willow_mpc_cost_y_hess(void);
extern int  willow_mpc_cost_y_hess_n_in(void);
extern int  willow_mpc_cost_y_hess_n_out(void);
extern int  willow_mpc_cost_y_hess_sparsity_in(int);
extern int  willow_mpc_cost_y_hess_sparsity_out(int);

extern void willow_mpc_cost_y_e_fun(void);
extern int  willow_mpc_cost_y_e_fun_n_in(void);
extern int  willow_mpc_cost_y_e_fun_n_out(void);
extern int  willow_mpc_cost_y_e_fun_sparsity_in(int);
extern int  willow_mpc_cost_y_e_fun_sparsity_out(int);

extern void willow_mpc_cost_y_e_fun_jac_ut_xt(void);
extern int  willow_mpc_cost_y_e_fun_jac_ut_xt_n_in(void);
extern int  willow_mpc_cost_y_e_fun_jac_ut_xt_n_out(void);
extern int  willow_mpc_cost_y_e_fun_jac_ut_xt_sparsity_in(int);
extern int  willow_mpc_cost_y_e_fun_jac_ut_xt_sparsity_out(int);

extern void willow_mpc_cost_y_e_hess(void);
extern int  willow_mpc_cost_y_e_hess_n_in(void);
extern int  willow_mpc_cost_y_e_hess_n_out(void);
extern int  willow_mpc_cost_y_e_hess_sparsity_in(int);
extern int  willow_mpc_cost_y_e_hess_sparsity_out(int);

#define MAP_CASADI_FNC(__CAP__, __BASE__) do {{ \\
    typedef int (*casadi_fun_t)(const double**, double**, int*, double*, void*); \\
    (__CAP__).casadi_fun = (casadi_fun_t) & __BASE__ ; \\
    (__CAP__).casadi_n_in = (int(*)(void)) & __BASE__ ## _n_in; \\
    (__CAP__).casadi_n_out = (int(*)(void)) & __BASE__ ## _n_out; \\
    (__CAP__).casadi_sparsity_in = (const int*(*)(int)) & __BASE__ ## _sparsity_in; \\
    (__CAP__).casadi_sparsity_out = (const int*(*)(int)) & __BASE__ ## _sparsity_out; \\
    (__CAP__).casadi_work = NULL; \\
}} while(0)

willow_mpc_solver_capsule * willow_mpc_acados_create_capsule(void) {{
    return (willow_mpc_solver_capsule*)calloc(1, sizeof(willow_mpc_solver_capsule));
}}

int willow_mpc_acados_free_capsule(willow_mpc_solver_capsule *cap) {{ free(cap); return 0; }}

int willow_mpc_acados_create(willow_mpc_solver_capsule *cap) {{
    int N = WILLOW_MPC_N, nx = WILLOW_MPC_NX, nu = WILLOW_MPC_NU;
    double tf = {TF};

    // plan
    cap->nlp_solver_plan = ocp_nlp_plan_create(N);

    // config
    cap->nlp_config = ocp_nlp_config_create(*cap->nlp_solver_plan);
    if (!cap->nlp_config) return -1;

    // dims
    cap->nlp_dims = ocp_nlp_dims_create(cap->nlp_config);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nx", &nx);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nu", &nu);
    int zero = 0;
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nz", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "np", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "ns", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nsbx",&zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nsbu",&zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nsg", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nsh", &zero);
    int nbx = WILLOW_MPC_NBX, nbu = WILLOW_MPC_NBU;
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nbx", &nbx);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nbu", &nbu);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "ng",  &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nh",  &zero);
    int nbx0 = WILLOW_MPC_NBX0;
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nbx_0",&nbx0);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nh_0", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "ns_0", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nsh_0",&zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nbx_e",&zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nh_e", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "ns_e", &zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nsh_e",&zero);
    ocp_nlp_dims_set_opt_vars(cap->nlp_config, cap->nlp_dims, "nr",   &zero);

    int ny0 = WILLOW_MPC_NY0, ny = WILLOW_MPC_NY, nyn = WILLOW_MPC_NYN;
    ocp_nlp_dims_set_cost(cap->nlp_config, cap->nlp_dims, 0, "ny", &ny0);
    ocp_nlp_dims_set_cost(cap->nlp_config, cap->nlp_dims, 1, "ny", &ny);
    ocp_nlp_dims_set_cost(cap->nlp_config, cap->nlp_dims, N, "ny", &nyn);

    // in / out
    cap->nlp_in  = ocp_nlp_in_create(cap->nlp_config, cap->nlp_dims);
    cap->nlp_out = ocp_nlp_out_create(cap->nlp_config, cap->nlp_dims);

    // External functions — assign CasADi function pointers ----------
    external_function_opts ext_fun_opts;
    external_function_opts_set_to_default(&ext_fun_opts);

    // dynamics (ERK: 1 per stage)
    cap->expl_ode_fun = (external_function_external_param_casadi*)malloc(sizeof(external_function_external_param_casadi)*N);
    cap->expl_vde_for = (external_function_external_param_casadi*)malloc(sizeof(external_function_external_param_casadi)*N);
    cap->expl_vde_adj = (external_function_external_param_casadi*)malloc(sizeof(external_function_external_param_casadi)*N);
    for (int i=0; i<N; i++) {{
        external_function_external_param_casadi_create(&cap->expl_ode_fun[i], &ext_fun_opts);
        external_function_external_param_casadi_create(&cap->expl_vde_for[i], &ext_fun_opts);
        external_function_external_param_casadi_create(&cap->expl_vde_adj[i], &ext_fun_opts);
        MAP_CASADI_FNC(cap->expl_ode_fun[i], willow_mpc_expl_ode_fun);
        MAP_CASADI_FNC(cap->expl_vde_for[i], willow_mpc_expl_vde_forw);
        MAP_CASADI_FNC(cap->expl_vde_adj[i], willow_mpc_expl_vde_adj);
    }}

    // path cost (stages 1..N-1)
    cap->cost_y_fun = (external_function_external_param_casadi*)malloc(sizeof(external_function_external_param_casadi)*(N-1));
    cap->cost_y_fun_jac_ut_xt = (external_function_external_param_casadi*)malloc(sizeof(external_function_external_param_casadi)*(N-1));
    cap->cost_y_hess = (external_function_external_param_casadi*)malloc(sizeof(external_function_external_param_casadi)*(N-1));
    for (int i=0; i<N-1; i++) {{
        external_function_external_param_casadi_create(&cap->cost_y_fun[i], &ext_fun_opts);
        external_function_external_param_casadi_create(&cap->cost_y_fun_jac_ut_xt[i], &ext_fun_opts);
        external_function_external_param_casadi_create(&cap->cost_y_hess[i], &ext_fun_opts);
        MAP_CASADI_FNC(cap->cost_y_fun[i], willow_mpc_cost_y_fun);
        MAP_CASADI_FNC(cap->cost_y_fun_jac_ut_xt[i], willow_mpc_cost_y_fun_jac_ut_xt);
        MAP_CASADI_FNC(cap->cost_y_hess[i], willow_mpc_cost_y_hess);
    }}

    // terminal cost
    external_function_external_param_casadi_create(&cap->cost_y_e_fun, &ext_fun_opts);
    external_function_external_param_casadi_create(&cap->cost_y_e_fun_jac_ut_xt, &ext_fun_opts);
    external_function_external_param_casadi_create(&cap->cost_y_e_hess, &ext_fun_opts);
    MAP_CASADI_FNC(cap->cost_y_e_fun, willow_mpc_cost_y_e_fun);
    MAP_CASADI_FNC(cap->cost_y_e_fun_jac_ut_xt, willow_mpc_cost_y_e_fun_jac_ut_xt);
    MAP_CASADI_FNC(cap->cost_y_e_hess, willow_mpc_cost_y_e_hess);

    // Set external functions on NLP model ---------------------------------
    for (int i=0; i<N; i++) {{
        ocp_nlp_dynamics_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, i,
            "expl_ode_fun", &cap->expl_ode_fun[i]);
        ocp_nlp_dynamics_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, i,
            "expl_vde_for", &cap->expl_vde_for[i]);
        ocp_nlp_dynamics_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, i,
            "expl_vde_adj", &cap->expl_vde_adj[i]);
    }}

    // path cost (stage 1..N-1)
    for (int i=0; i<N-1; i++) {{
        ocp_nlp_cost_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, i+1,
            "nls_y_fun", &cap->cost_y_fun[i]);
        ocp_nlp_cost_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, i+1,
            "nls_y_fun_jac", &cap->cost_y_fun_jac_ut_xt[i]);
        ocp_nlp_cost_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, i+1,
            "nls_y_hess", &cap->cost_y_hess[i]);
    }}

    // terminal cost (stage N)
    ocp_nlp_cost_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, N,
        "nls_y_fun", &cap->cost_y_e_fun);
    ocp_nlp_cost_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, N,
        "nls_y_fun_jac", &cap->cost_y_e_fun_jac_ut_xt);
    ocp_nlp_cost_model_set_external_param_fun(cap->nlp_config, cap->nlp_dims, cap->nlp_in, N,
        "nls_y_hess", &cap->cost_y_e_hess);

    // options ----------------------------------------------------------
    cap->nlp_opts = ocp_nlp_solver_opts_create(cap->nlp_config, cap->nlp_dims);
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "qp_solver",       (void*)"FULL_CONDENSING_HPIPM");
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "hessian_approx",  (void*)"GAUSS_NEWTON");
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "integrator_type", (void*)"ERK");
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "nlp_solver_type", (void*)"SQP_RTI");
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "globalization",   (void*)"FIXED_STEP");
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "N_horizon", &N);
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "tf", &tf);
    double lm = 1e-4; int max_iter = 5;
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "levenberg_marquardt", &lm);
    ocp_nlp_solver_opts_set_at_stage(cap->nlp_config, cap->nlp_opts, 0, "nlp_solver_max_iter", &max_iter);

    // solver
    cap->nlp_solver = ocp_nlp_solver_create(cap->nlp_config, cap->nlp_dims, cap->nlp_opts, cap->nlp_in);
    if (!cap->nlp_solver) return -3;

    // cost weights ---------------------------------------------------
    double W_data[{NY_SQ}] = {{ {W_DATA} }};
    double W_e_data[{NYE_SQ}] = {{ {WE_DATA} }};
    ocp_nlp_cost_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, 1, "W", W_data);
    ocp_nlp_cost_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, N, "W", W_e_data);

    // bounds ---------------------------------------------------------
    double lbx[{NX}]   = {{ {LBX_DATA} }};
    double ubx[{NX}]   = {{ {UBX_DATA} }};
    double lbu[{NU}]   = {{ {LBU_DATA} }};
    double ubu[{NU}]   = {{ {UBU_DATA} }};
    double lbx0[{NX}]  = {{ {LBX0_DATA} }};
    double ubx0[{NX}]  = {{ {UBX0_DATA} }};
    int idxbx[{NX}];   for (int i=0; i<{NX}; i++) idxbx[i] = i;
    int idxbu[{NU}];   for (int i=0; i<{NU}; i++) idxbu[i] = i;
    int idxbx0[{NX}];  for (int i=0; i<{NX}; i++) idxbx0[i] = i;

    for (int i=1; i<N; i++) {{
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, i, "lbx", lbx);
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, i, "ubx", ubx);
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, i, "idxbx", idxbx);
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, i, "lbu", lbu);
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, i, "ubu", ubu);
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, i, "idxbu", idxbu);
    }}
    ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, 0, "lbx", lbx0);
    ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, 0, "ubx", ubx0);
    ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, 0, "idxbx", idxbx0);
    ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, 0, "lbu", lbu);
    ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, 0, "ubu", ubu);
    ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, 0, "idxbu", idxbu);
    if (N>1) {{
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, N, "lbx", lbx);
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, N, "ubx", ubx);
        ocp_nlp_constraints_model_set(cap->nlp_config, cap->nlp_dims, cap->nlp_in, cap->nlp_out, N, "idxbx", idxbx);
    }}

    cap->nlp_np = WILLOW_MPC_NP;
    return 0;
}}

int willow_mpc_acados_solve(willow_mpc_solver_capsule *cap) {{
    ocp_nlp_precompute(cap->nlp_solver, cap->nlp_in, cap->nlp_out);
    return ocp_nlp_solve(cap->nlp_solver, cap->nlp_in, cap->nlp_out);
}}

int willow_mpc_acados_free(willow_mpc_solver_capsule *cap) {{
    for (int i=0; i<WILLOW_MPC_N; i++) {{
        external_function_external_param_casadi_free(&cap->expl_ode_fun[i]);
        external_function_external_param_casadi_free(&cap->expl_vde_for[i]);
        external_function_external_param_casadi_free(&cap->expl_vde_adj[i]);
    }}
    free(cap->expl_ode_fun); free(cap->expl_vde_for); free(cap->expl_vde_adj);
    for (int i=0; i<WILLOW_MPC_N-1; i++) {{
        external_function_external_param_casadi_free(&cap->cost_y_fun[i]);
        external_function_external_param_casadi_free(&cap->cost_y_fun_jac_ut_xt[i]);
        external_function_external_param_casadi_free(&cap->cost_y_hess[i]);
    }}
    free(cap->cost_y_fun); free(cap->cost_y_fun_jac_ut_xt); free(cap->cost_y_hess);
    external_function_external_param_casadi_free(&cap->cost_y_e_fun);
    external_function_external_param_casadi_free(&cap->cost_y_e_fun_jac_ut_xt);
    external_function_external_param_casadi_free(&cap->cost_y_e_hess);

    ocp_nlp_in_destroy(cap->nlp_in);
    ocp_nlp_out_destroy(cap->nlp_out);
    ocp_nlp_solver_destroy(cap->nlp_solver);
    ocp_nlp_solver_opts_destroy(cap->nlp_opts);
    ocp_nlp_plan_destroy(cap->nlp_solver_plan);
    ocp_nlp_config_destroy(cap->nlp_config);
    ocp_nlp_dims_destroy(cap->nlp_dims);
    return 0;
}}

ocp_nlp_in     *willow_mpc_acados_get_nlp_in(willow_mpc_solver_capsule *c)     {{ return c->nlp_in; }}
ocp_nlp_out    *willow_mpc_acados_get_nlp_out(willow_mpc_solver_capsule *c)    {{ return c->nlp_out; }}
ocp_nlp_solver *willow_mpc_acados_get_nlp_solver(willow_mpc_solver_capsule *c) {{ return c->nlp_solver; }}
ocp_nlp_config *willow_mpc_acados_get_nlp_config(willow_mpc_solver_capsule *c) {{ return c->nlp_config; }}
void           *willow_mpc_acados_get_nlp_opts(willow_mpc_solver_capsule *c)   {{ return c->nlp_opts; }}
ocp_nlp_dims   *willow_mpc_acados_get_nlp_dims(willow_mpc_solver_capsule *c)   {{ return c->nlp_dims; }}
ocp_nlp_plan_t *willow_mpc_acados_get_nlp_plan(willow_mpc_solver_capsule *c)   {{ return c->nlp_solver_plan; }}
"""


def generate_solver_wrapper(outdir, meta):
    """手动生成 acados solver 包装 C/H 文件, 避免 tera 依赖."""
    gen_dir = os.path.join(outdir, 'c_generated_code')
    os.makedirs(gen_dir, exist_ok=True)

    nx, nu, nq, horizon, dt = meta['nx'], meta['nu'], meta['nq'], meta['horizon'], meta['dt']
    ny, ny_e = meta['ny'], meta['ny_e']

    # 权重矩阵 (flattened row-major)
    W_pos  = np.diag([10., 10., 10.])
    W_vel  = np.diag([1.]*nq)
    W_tau  = np.diag([0.01]*nu)
    Wpose  = np.diag([50., 50., 50.])
    Wvele  = np.diag([2.]*nq)

    W = ca.diagcat(W_pos, W_vel, W_tau).full().flatten()
    We = ca.diagcat(Wpose, Wvele).full().flatten()

    q_l = meta['q_lower']; q_u = meta['q_upper']
    dq_l = -meta['dq_limit']; dq_u = meta['dq_limit']
    tau_l = -meta['tau_limit']; tau_u = meta['tau_limit']

    lbx0 = np.concatenate([np.full(nq, -1e6), dq_l])
    ubx0 = np.concatenate([np.full(nq,  1e6), dq_u])
    lbx  = np.concatenate([q_l, dq_l]); ubx = np.concatenate([q_u, dq_u])
    lbu  = tau_l; ubu = tau_u

    def arr_strC(a, fmt='{:.10e}'):
        return ', '.join(fmt.format(v) if abs(v) != 1e6 else ('-1e6' if v < 0 else '1e6') for v in a)

    hpp = SOLVER_HEADER_TEMPLATE.format(NX=nx, NU=nu, NY=ny, NYE=ny_e, HORIZON=horizon)
    with open(os.path.join(gen_dir, 'acados_solver_willow_mpc.h'), 'w') as f:
        f.write(hpp)

    cpp = SOLVER_SOURCE_TEMPLATE.format(
        NX=nx, NU=nu, NY=ny, NYE=ny_e, HORIZON=horizon,
        TF=horizon*dt,
        NY_SQ=ny*ny, NYE_SQ=ny_e*ny_e,
        W_DATA=arr_strC(W), WE_DATA=arr_strC(We),
        LBX_DATA=arr_strC(lbx), UBX_DATA=arr_strC(ubx),
        LBU_DATA=arr_strC(lbu), UBU_DATA=arr_strC(ubu),
        LBX0_DATA=arr_strC(lbx0), UBX0_DATA=arr_strC(ubx0),
    )
    with open(os.path.join(gen_dir, 'acados_solver_willow_mpc.c'), 'w') as f:
        f.write(cpp)


def generate_cpp_traits(outdir, meta, traits_name):
    detail_ns = re.sub(r'(?<!^)(?=[A-Z])', '_', traits_name).lower()
    out_path = os.path.join(outdir, f'{traits_name}.hpp')

    nx, nu, nq, horizon, dt = meta['nx'], meta['nu'], meta['nq'], meta['horizon'], meta['dt']

    hpp = f"""#pragma once
// ---------------------------------------------------------
// urdf2mpc.py auto-generated — DO NOT EDIT!
// DOF:{nq}  H:{horizon}  dt:{dt*1000:.0f}ms  nx:{nx}  nu:{nu}
//
// 此文件仅包含轻量 C++ traits 封装。
// 实际 C 实现文件位于:
//   generated/c_generated_code/acados_solver_willow_mpc.c
//   generated/c_generated_code/willow_mpc_model/*.c
//   generated/c_generated_code/willow_mpc_cost/*.c
// ---------------------------------------------------------

#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <cstdlib>

// acados solver wrapper (manually generated, compiled as separate .c)
extern "C" {{
#include "acados_solver_willow_mpc.h"
}}

namespace florid {{

struct {traits_name} {{
    static constexpr int kNX      = {nx};
    static constexpr int kNU      = {nu};
    static constexpr int kDOF     = {nq};
    static constexpr int kHorizon = {horizon};
    static constexpr float kDt    = {dt}f;

    static constexpr float kQLower[{nq}]   = {{{ ', '.join(f'{v}f' for v in meta['q_lower']) }}};
    static constexpr float kQUpper[{nq}]   = {{{ ', '.join(f'{v}f' for v in meta['q_upper']) }}};
    static constexpr float kTauLimit[{nu}] = {{{ ', '.join(f'{v}f' for v in meta['tau_limit']) }}};
    static constexpr float kDqLimit[{nq}]  = {{{ ', '.join(f'{v}f' for v in meta['dq_limit']) }}};

    static void* create() {{
        auto* cap = willow_mpc_acados_create_capsule();
        willow_mpc_acados_create(cap);
        return cap;
    }}

    static void destroy(void* cap) {{
        auto* c = static_cast<willow_mpc_solver_capsule*>(cap);
        willow_mpc_acados_free(c);
        willow_mpc_acados_free_capsule(c);
    }}

    static void setInitialState(void* cap, const float* x0) {{
        auto* c = static_cast<willow_mpc_solver_capsule*>(cap);
        ocp_nlp_constraints_model_set(c->nlp_config, c->nlp_dims, c->nlp_in, c->nlp_out,
            0, "lbx", const_cast<float*>(x0));
        ocp_nlp_constraints_model_set(c->nlp_config, c->nlp_dims, c->nlp_in, c->nlp_out,
            0, "ubx", const_cast<float*>(x0));
    }}

    static void setReference(void* cap, const float* pos_ref) {{
        float yref[{meta['ny']}] = {{}};
        yref[0] = pos_ref[0]; yref[1] = pos_ref[1]; yref[2] = pos_ref[2];
        float yref_e[{meta['ny_e']}] = {{}};
        yref_e[0] = pos_ref[0]; yref_e[1] = pos_ref[1]; yref_e[2] = pos_ref[2];

        auto* c = static_cast<willow_mpc_solver_capsule*>(cap);
        for (int i = 0; i < {horizon}; ++i)
            ocp_nlp_cost_model_set(c->nlp_config, c->nlp_dims, c->nlp_in, i, "yref", yref);
        ocp_nlp_cost_model_set(c->nlp_config, c->nlp_dims, c->nlp_in, {horizon}, "yref", yref_e);
    }}

    static int solve(void* cap) {{
        return willow_mpc_acados_solve(static_cast<willow_mpc_solver_capsule*>(cap));
    }}

    static void getOptimalQ(void* cap, float* q_out) {{
        auto* c = static_cast<willow_mpc_solver_capsule*>(cap);
        float x_traj[{nx}];
        ocp_nlp_out_get(c->nlp_config, c->nlp_dims, c->nlp_out, 0, "x", x_traj);
        std::memcpy(q_out, x_traj, {nq} * sizeof(float));
    }}

    static void getOptimalDq(void* cap, float* dq_out) {{
        auto* c = static_cast<willow_mpc_solver_capsule*>(cap);
        float x_traj[{nx}];
        ocp_nlp_out_get(c->nlp_config, c->nlp_dims, c->nlp_out, 0, "x", x_traj);
        std::memcpy(dq_out, &x_traj[{nq}], {nq} * sizeof(float));
    }}
}};

}} // namespace florid
"""
    with open(out_path, 'w') as f:
        f.write(hpp)
    print(f"-> {out_path}  ({os.path.getsize(out_path):,} bytes)")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--urdf',    required=True)
    parser.add_argument('--outdir',  default='generated')
    parser.add_argument('--name',    default='WillowMPCTraits')
    parser.add_argument('--horizon', type=int,   default=5)
    parser.add_argument('--dt',      type=float, default=0.004)
    args = parser.parse_args()

    outdir_abs = os.path.abspath(args.outdir)
    os.makedirs(outdir_abs, exist_ok=True)

    print(f"URDF: {args.urdf}")
    f_expl, f_impl, x, u, xdot, fk_trans = build_explicit_dynamics(args.urdf)

    print(f"Building OCP  H={args.horizon}  dt={args.dt*1000:.0f}ms")
    ocp, meta = build_acados_ocp(f_expl, f_impl, x, u, xdot, fk_trans,
                                  horizon=args.horizon, dt=args.dt)
    print(f"  nx={meta['nx']}  nu={meta['nu']}  nq={meta['nq']}")

    code_gen_dir = os.path.join(outdir_abs, 'c_generated_code')
    json_path = os.path.join(outdir_abs, 'acados_ocp_willow.json')

    ocp.name = ocp.model.name
    ocp.code_gen_options.code_export_directory = code_gen_dir
    ocp.code_gen_options.json_file = json_path
    ocp.code_gen_options.casadi_code_gen_options = {
        "mex": False, "casadi_int": "int", "casadi_real": "double",
    }

    print("Generating CasADi external functions ...")
    ocp.generate_external_functions()

    print("Writing solver wrapper ...")
    generate_solver_wrapper(outdir_abs, meta)

    print("Wrapping into C++ traits ...")
    generate_cpp_traits(outdir_abs, meta, args.name)
    print("Done.")


if __name__ == '__main__':
    main()
