# SPDX-License-Identifier: ISC
cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/FloridWirelinkSnapshot.cmake")
if(NOT LF_SNAPSHOT_MODE MATCHES "^(update|check)$")
    message(FATAL_ERROR "LF_SNAPSHOT_MODE must be update or check")
endif()
foreach(_required IN ITEMS LF_SOURCE_DIR LF_CODEC_DIR LF_RUNTIME_DIR LF_STAGING_DIR
        WIRELINK_WLC_VERSION WIRELINK_WLC_CODEGEN_ABI)
    if(NOT DEFINED ${_required} OR "${${_required}}" STREQUAL "")
        message(FATAL_ERROR "Missing ${_required}")
    endif()
endforeach()

# Copy only compiler artifacts, never stamps or build-system state.
file(MAKE_DIRECTORY "${LF_STAGING_DIR}/codec" "${LF_STAGING_DIR}/host")
foreach(_file IN ITEMS fci_device.c fci_device.h fci_device_values.h fci_device_bindings.c
        fci_device_bindings.h fci_device_manifest.json)
    configure_file("${LF_CODEC_DIR}/${_file}" "${LF_STAGING_DIR}/codec/${_file}" COPYONLY)
endforeach()
foreach(_file IN ITEMS fci_device_runtime.c fci_device_runtime.h fci_device_endpoint.h
        fci_device_advanced.h fci_device_runtime_manifest.json)
    configure_file("${LF_RUNTIME_DIR}/${_file}" "${LF_STAGING_DIR}/host/${_file}" COPYONLY)
endforeach()
lf_wirelink_snapshot_content("${LF_SOURCE_DIR}" "${LF_STAGING_DIR}" _fresh)
set(_snapshot "${LF_SOURCE_DIR}/generated/wirelink")
if(LF_SNAPSHOT_MODE STREQUAL "update")
    foreach(_file IN LISTS LF_WIRELINK_SNAPSHOT_OUTPUTS)
        configure_file("${LF_STAGING_DIR}/${_file}" "${_snapshot}/${_file}" COPYONLY)
    endforeach()
    file(WRITE "${_snapshot}/snapshot.txt" "${_fresh}")
    message(STATUS "Updated ${_snapshot}; commit this directory with the inputs")
else()
    lf_wirelink_snapshot_content("${LF_SOURCE_DIR}" "${_snapshot}" _checked_in)
    if(NOT EXISTS "${_snapshot}/snapshot.txt")
        lf_wirelink_snapshot_error("Missing snapshot.txt")
    endif()
    file(READ "${_snapshot}/snapshot.txt" _recorded)
    string(REPLACE "\r\n" "\n" _recorded "${_recorded}")
    if(NOT _fresh STREQUAL _checked_in OR NOT _fresh STREQUAL _recorded)
        lf_wirelink_snapshot_error("Checked-in FCI bindings differ from a fresh WLC build")
    endif()
    message(STATUS "Checked-in FCI bindings match a fresh WLC build")
endif()
