name: Test

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ninja-build

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Configure
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure -j$(nproc)

      - name: Test Verbose (on failure)
        if: failure()
        run: |
          cd build
          ctest --output-on-failure --verbose -j1
